gui things, help me get values from the lists and suggest other things to do!
bhs-intro-to-programming/physics-2D-sim pull request #20
Opened 2023-01-18 23:26 UTC by ionisea

we may want to use values for each shape instead;
0 = line
1= circle
etc

either way please make sure the other things are to your liking and mr seibel please make sure this won't break anything else, I didn't know where to put it besides index

2023-01-18 23:32 UTC, lashlockbhs commented
"document.getElementById("").value" to get value of input?

2023-01-19 02:14 UTC, gigamonkey reviewed
I'm pretty sure `bottom` is not a valid value for the `margin` property. In which case it probably gets turned into 0 which may look fine. But I'm not sure what you're actually trying to do there. Everything else looks reasonable.

2023-01-19 02:14 UTC, gigamonkey commented on projects/physics/public/style.css
> +  margin: 1in bottom;
eh? what does that do?

2023-01-19 02:14 UTC, gigamonkey commented on projects/physics/public/index.html
> +  <input type="number" id="density" name="density"
You may also want to look at `<input type="range">`

2023-01-19 22:34 UTC, ionisea commented on projects/physics/public/style.css
> +  margin: 1in bottom;
nothing, removed

2023-01-19 22:39 UTC, ionisea commented on projects/physics/public/index.html
> +  <input type="number" id="density" name="density"
I tried this but it doesn't really fit the idea of this we've had and I think im going to keep using number

2023-01-19 23:12 UTC, ionisea commented
@lashlockbhs i need you to figure out the on key down stuff I have no clue how it works

2023-01-19 23:26 UTC, lashlockbhs requested changes
Fix what I suggested and figure out how do register functions based on the specific key pressed.

2023-01-19 23:26 UTC, lashlockbhs commented on projects/physics/public/perfectShapes.js
> +document.getContext('')
remove cause wrong

2023-01-19 23:26 UTC, lashlockbhs commented on projects/physics/public/script.js
> +  onKeyDown,
change name. to similar to other func

2023-01-19 23:26 UTC, lashlockbhs commented on projects/physics/public/script.js
> +    objArray.push(new Shape(10, [vector(0, 0)], vertices, area * document.getElementById('density').getAttribute('value')));
move function to math.js.

2023-01-19 23:26 UTC, szetingchen reviewed
lgtm



(i didnt look, if it breaks its lukes fault)

2023-01-20 22:50 UTC, ionisea commented on projects/physics/public/script.js
> +    objArray.push(new Shape(10, [vector(0, 0)], vertices, area * document.getElementById('density').getAttribute('value')));
done

2023-01-20 22:50 UTC, ionisea commented on projects/physics/public/script.js
> +  onKeyDown,
removed from import, I don't know how it works

2023-01-21 20:42 UTC, gigamonkey commented on projects/physics/public/index.html
> +  <input type="number" id="density" name="density"
👍🏻

2023-01-21 20:48 UTC, gigamonkey reviewed
All looks pretty reasonable to me.

2023-01-21 20:48 UTC, gigamonkey commented on projects/physics/public/script.js
> +    animateStart = animateStart ? false : true
You can also write this more concisely and more idiomatically as:

```javascript
    animateStart = !animateStart; 
```

2023-01-21 20:48 UTC, gigamonkey commented on projects/physics/public/index.html
> +            <label for="perfectShape">-- Perfect Shapes (check README.md) --</label>
The `for` attribute of a `label` is supposed to be the value of the `id` attribute of the element it's a label for. I think you mean this to be `shape-select`?

2023-01-21 20:48 UTC, gigamonkey commented on projects/physics/public/index.html
> +            <label for="perfectShape">-- Perfect Shapes (check README.md) --</label>
This indentation is a bit wonky. I think the editor's "Format document" command would clean it up.

2023-01-21 20:48 UTC, gigamonkey commented on projects/physics/public/script.js
> +const FPS = 12 // frames per second, consider changing to ms/frame
You don't seem to actually be using this for anything. You should either delete it or finish whatever idea you had.

2023-01-21 23:26 UTC, lashlockbhs approved these changes
lgtm.

2023-01-23 22:59 UTC, ionisea commented
> "document.getElementById("").value" to get value of input?

ill figure this out later

2023-01-23 23:00 UTC, ionisea commented
>  figure out how do register functions based on the specific key pressed.
thats your job

2023-01-23 23:23 UTC, szetingchen approved these changes
lgtm

2023-01-23 23:24 UTC, merged