Gui-Final
bhs-intro-to-programming/physics-2D-sim pull request #27
Opened 2023-02-10 23:29 UTC by lashlockbhs

Gui that works for all our purposes, perfect shapes still needs to be added. This will count as my project for grading, aswell as my other contributions to physics.

2023-02-10 23:31 UTC, szetingchen approved these changes
simply the worst gui I have ever seen
most inefficient code ever

but it works so lgtm

2023-02-13 00:48 UTC, ionisea requested changes
change or reply to comments with justification and re-request my review

2023-02-13 00:48 UTC, ionisea commented on projects/physics/public/script.js
> +      const density = parseInt(document.getElementById(shape.menu.name + " density").value)
This is a weird way to do density/mass, as you demonstrated on friday. While it clearly works, I don't think a dynamic density makes much sense for this specific circumstance. I recommend you open up a window once, when the shape is first drawn, just to change the density, then close it when the the field is deselected.

2023-02-13 00:48 UTC, ionisea commented on projects/physics/public/style.css
> +  font-family:system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
Are we going to use @szetingchen's lexend font here?

2023-02-13 20:11 UTC, lashlockbhs commented on projects/physics/public/script.js
> +      const density = parseInt(document.getElementById(shape.menu.name + " density").value)
I agree that it doesn't make sence to be able to modify density durning the sim, one could argue that there should be no modifications to shape properties by the user during the sim, but its kinda funny to expirement with these type of modifiable properties.

2023-02-13 20:12 UTC, lashlockbhs commented on projects/physics/public/style.css
> +  font-family:system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
we can change font in later lets just get this shit merged.

2023-02-13 20:26 UTC, ionisea approved these changes
In that case lgtm

2023-02-19 21:43 UTC, gigamonkey approved these changes
I had a bit of trouble using the GUI but obviously you've done a ton of interesting work here. Your project grade will be posted in IC soon.

2023-02-21 17:59 UTC, lashlockbhs commented
If you have problems with it your prob using it incorrectly sorry.

2023-02-23 21:48 UTC, merged