added math.js
bhs-intro-to-programming/physics-2D-sim pull request #9
Opened 2023-01-07 05:54 UTC by szetingchen

mostly directed at Ion to check my math

2023-01-07 06:01 UTC, lashlockbhs reviewed
import into script.js aswell.

2023-01-07 06:06 UTC, lashlockbhs commented on projects/physics/public/script.js
> +import {add2Vectors, vectorMultiply, addNumVectors, sigma, pi, velocity} from './math.js';
lgtm

2023-01-07 06:06 UTC, lashlockbhs approved these changes

2023-01-07 15:53 UTC, gigamonkey reviewed
I'm going to to let you all take care of approving each other's changes but you should probably read my comments.

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +const pi = (start, end, funct) => {
I guess that's the name of the symbol but it's maybe confusing since most people would probably think you're talking about the constant. (3.1415...). I'd probably go with `sum` and `product` rather than `sigma` and `pi`.

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +const vector = (angle, magnitude) => {
In a case like this you should probably document (with a comment) that the argument is in degrees but is stored in radians. At the very least, change the `angle` argument to `degrees` so someone looking at this knows what's expected.

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +  return ({ angle, magnitude: mag });
don't need the `()`s around the expression.

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +const add2Vectors = (a) => {
`a` is not a great name—I have to read the code and see how it's used to figure out that it's a two element array of vectors. And it feels like this might be better written to take the two vectors as separate arguments, e.g. `add2Vectors(v1, v2)` or even `add2Vectors(a, b)` would be okay. Writing it that way also has the nice effect that than you could use it with reduce:

```javascript
aBunchOfVectors.reduce(add2Vectors, vector(0, 0))
```

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +  const mag = Math.sqrt((x1 + x2) ** 2 + (y1 + y2) ** 2);
I know I've made you write this a bunch of time in exercises but there's actually a built in function to do this for you:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +  return a.reduce((acc, x) => add2Vectors([acc, x]), vector(0, 0));
Yeah, see how this would be shorter if you had written `add2Vectors` to take two arguments.

2023-01-07 15:53 UTC, gigamonkey commented on projects/physics/public/math.js
> +    return ({ angle: o.angle + Math.PI, magnitude: o.magnitude * -n });
Do you need to do anything to keep the angles in the range `[0, 2*Math.PI)`. I.e. if I have a vector whose angle is close to `2 * Math.PI` and I multiply it by a negative number it should wrap around, right?

2023-01-07 17:16 UTC, gigamonkey reviewed
Revising on of my earlier comments.

2023-01-07 17:16 UTC, gigamonkey commented on projects/physics/public/math.js
> +const pi = (start, end, funct) => {
Actually, I take that back, since I'd actually expect `sum` and `product` to be functions that add up or multiply together element of a list. So `sigma` and `pi` are fine.

Just for grins, however, you should try to write a helper function that captures the common structure of these two functions such that you could define these two functions like this:

```javascript
const sigma = (start, end, fn) => overRange(start, end, (acc, n) => acc + fn(n), 0);

const pi = (start, end, fn) => overRange(start, end, (acc, n) => acc * fn(n), 1);
```

2023-01-07 17:27 UTC, ionisea requested changes
fix the stuff Mr. Seibel and I mentioned and this'll be good to roll I reckon

2023-01-07 17:27 UTC, ionisea commented on projects/physics/public/math.js
> +const velocity = (force, time) => {
this should also take a direction, and maybe be converted all the way down to displacement rather than velocity for our frame changes

each shape should additionally have a currentAcceleration and velocity attribute that is saved and edited each frame because you can't extrapolate past acceleration/velocity from current force.

2023-01-07 17:27 UTC, ionisea commented on projects/physics/public/script.js
> +import {add2Vectors, vectorMultiply, addNumVectors, sigma, pi, velocity} from './math.js';
I've made some convenience functions that should work here if you want to add them, please verify that they'll work first though;
const degToRad = (radAngle) => radAngle * Math.PI / 180
const radToDeg = (degAngle) => degAngle * 180 / Math.PI
const avg = (array) => array.reduce((a,e) => a+e, 0) /  array.length
const twoPointAngle = (a, b) => Math.atan2(b.y - a.y, b.x - a.x)
const twoPointDist = (a, b) => Math.hypot(Math.abs(a.x-b.x), Math.abs(a.y-b.y))

2023-01-07 17:27 UTC, ionisea commented on projects/physics/public/math.js
> +
```suggestion
const getAcceleration = (force, mass, appliedTime) => force/mass*appliedTime
const getVelocity = (force, mass, appliedTime, fps) => getAcceleration(force, mass, appliedTime) * (1/fps)
//const getDisplacement = (force, mass, appliedTime, fps, angle) => getVelocity(force, mass, appliedTime, fps) / (1/fps) // use trig for coordinate displacement w/ angle
```

2023-01-07 17:47 UTC, gigamonkey commented on projects/physics/public/script.js
> +import {add2Vectors, vectorMultiply, addNumVectors, sigma, pi, velocity} from './math.js';
You can write functions in shorthand syntax that return objects like this:

```javascript
const vector = (angle, magnitude) => ({angle, magnitude});
```

The `()`s prevent the `{}`s as being interpreted as the function body braces. Or, as you suggested:

```javascript
const vector = (angle, magnitude) => (
  return {angle, magnitude};
);
```

But I'd advise breaking it over multiple lines if you're not using shorthand form.

2023-01-07 18:12 UTC, ionisea commented on projects/physics/public/script.js
> +import {add2Vectors, vectorMultiply, addNumVectors, sigma, pi, velocity} from './math.js';
alright, I'll keep that in mind

2023-01-08 03:20 UTC, lashlockbhs commented on projects/physics/public/math.js
> +
lets get this done so we can start implementing the rest of our code into the new enviro.

2023-01-08 06:25 UTC, szetingchen commented on projects/physics/public/math.js
> +const add2Vectors = (a) => {
not sure how 
aBunchOfVectors.reduce(add2Vectors, vector(0, 0))
works. I thought we needed a accumulator? I've rewitten the function as 
const addNumVectors = (vectors) => {
  return vectors.reduce((acc, x) => add2Vectors(acc, x), vector(0, 0));
};

2023-01-08 19:09 UTC, gigamonkey commented on projects/physics/public/math.js
> +const add2Vectors = (a) => {
Look at the expression:

```javascript
vectors.reduce((acc, x) => add2Vectors(acc, x), vector(0, 0));
```

You're writing an anonymous function: `(acc, x) => add2Vectors(acc, x)` that takes two arguments (`acc` and `x`) and then just calls `add2Vectors` with those same two arguments. There's no need for the anonymous function as you can just pass `add2Vectors` as it's already a function that takes two arguments:

```javascript
vectors.reduce(add2Vectors, vector(0, 0));
```

I.e. the first argument to `add2Vectors` is the accumulator and the second argument is the new value.

If you want to try a simpler example:

```javascript
const add = (a, b) => a + b;

[1,2,3,4].reduce(add, 0)
``` 

BTW, you should read https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax about how to use Markdown to format your PR comments nicely. In particular using code blocks. Though I think the thing that is most useful is https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks about making code blocks.

2023-01-08 19:13 UTC, gigamonkey reviewed
Demonstrating making code suggestions in PR comments.

2023-01-08 19:13 UTC, gigamonkey commented on projects/physics/public/math.js
> +  return ({ angle, magnitude: mag });
Mostly just to show you a Github feature, here's a suggestion which I created by clicking this icon:

![2023-01-08 at 11 12 AM](https://user-images.githubusercontent.com/250053/211214437-86f09589-4fa5-49fe-bfc6-a5dc79df4f2d.png)

```suggestion
  const magnitude = Math.hypot((x1 - x2), (y1 - y2));
  return { angle, magnitude };
```

You should be able to accept this charge directly into the PR by clicking a button.

2023-01-09 04:30 UTC, lashlockbhs reviewed
```javascript

const distance = (p1, p2) => Math.hypot(p1.x -p2.x, p1.y - p2.y)

```

Add this func to **math.js**.

2023-01-09 04:34 UTC, lashlockbhs commented
The new commit looks like it implements what Ion suggested aswell. Once you add the **distance** function I will approve.

2023-01-09 17:49 UTC, gigamonkey reviewed
This is looking good. I'd advise that you merge this soon so everyone has access to your code but then you should probably go back and write more unit tests for all these functions since if they don't work, nothing else will.

2023-01-09 22:35 UTC, gigamonkey commented
> ```js
> const distance = (p1, p2) => Math.hypot(p1.x -p2.x, p1.y - p2.y)
> ```
> 
> Add this func to **math.js**.

Just as a process note, everything will generally go faster if you approve PRs as long as they don't introduce bugs. If you want something added you can always make your own PR to do so and in the meantime everyone else gets to start workin with the new code rather than waiting for another round of edits, reviews, etc.

2023-01-09 23:03 UTC, lashlockbhs approved these changes
Looks good, like Mr. Seibel said we should make a file for tests to make sure everything works.

2023-01-09 23:11 UTC, ionisea approved these changes
go ahead do it

2023-01-09 23:15 UTC, merged